syntax = "proto3";

package shipment.v1;

option go_package = "github.com/vonMeumann/shipment-grpc-service/api/proto/shipment/v1;shipmentv1";

import "google/protobuf/timestamp.proto";

service ShipmentService {
  rpc CreateShipment(CreateShipmentRequest) returns (CreateShipmentResponse);
  rpc GetShipment(GetShipmentRequest) returns (GetShipmentResponse);
  rpc AddShipmentEvent(AddShipmentEventRequest) returns (AddShipmentEventResponse);
  rpc GetShipmentHistory(GetShipmentHistoryRequest) returns (GetShipmentHistoryResponse);
}

message Shipment {
  string reference_number = 1;
  string origin = 2;
  string destination = 3;
  string current_status = 4;
  string driver_details = 5;
  string unit_details = 6;
  double shipment_amount = 7;
  double driver_revenue = 8;
}

message StatusEvent {
  string shipment_ref = 1;
  string status = 2;
  google.protobuf.Timestamp timestamp = 3;
  string remarks = 4;
}

message CreateShipmentRequest {
  string reference_number = 1;
  string origin = 2;
  string destination = 3;
  string driver_details = 4;
  string unit_details = 5;
  double shipment_amount = 6;
  double driver_revenue = 7;
}

message CreateShipmentResponse {
  string reference_number = 1;
}

message GetShipmentRequest {
  string reference_number = 1;
}

message GetShipmentResponse {
  Shipment shipment = 1;
}

message AddShipmentEventRequest {
  string reference_number = 1;
  string status = 2;
  string remarks = 3;
}

message AddShipmentEventResponse {
  bool success = 1;
}

message GetShipmentHistoryRequest {
  string reference_number = 1;
}

message GetShipmentHistoryResponse {
  repeated StatusEvent events = 1;
}
