// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: api/proto/shipment/v1/shipment.proto

package shipmentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Shipment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReferenceNumber string                 `protobuf:"bytes,1,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	Origin          string                 `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination     string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	CurrentStatus   string                 `protobuf:"bytes,4,opt,name=current_status,json=currentStatus,proto3" json:"current_status,omitempty"`
	DriverDetails   string                 `protobuf:"bytes,5,opt,name=driver_details,json=driverDetails,proto3" json:"driver_details,omitempty"`
	UnitDetails     string                 `protobuf:"bytes,6,opt,name=unit_details,json=unitDetails,proto3" json:"unit_details,omitempty"`
	ShipmentAmount  float64                `protobuf:"fixed64,7,opt,name=shipment_amount,json=shipmentAmount,proto3" json:"shipment_amount,omitempty"`
	DriverRevenue   float64                `protobuf:"fixed64,8,opt,name=driver_revenue,json=driverRevenue,proto3" json:"driver_revenue,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Shipment) Reset() {
	*x = Shipment{}
	mi := &file_api_proto_shipment_v1_shipment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shipment) ProtoMessage() {}

func (x *Shipment) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shipment_v1_shipment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shipment.ProtoReflect.Descriptor instead.
func (*Shipment) Descriptor() ([]byte, []int) {
	return file_api_proto_shipment_v1_shipment_proto_rawDescGZIP(), []int{0}
}

func (x *Shipment) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *Shipment) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Shipment) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Shipment) GetCurrentStatus() string {
	if x != nil {
		return x.CurrentStatus
	}
	return ""
}

func (x *Shipment) GetDriverDetails() string {
	if x != nil {
		return x.DriverDetails
	}
	return ""
}

func (x *Shipment) GetUnitDetails() string {
	if x != nil {
		return x.UnitDetails
	}
	return ""
}

func (x *Shipment) GetShipmentAmount() float64 {
	if x != nil {
		return x.ShipmentAmount
	}
	return 0
}

func (x *Shipment) GetDriverRevenue() float64 {
	if x != nil {
		return x.DriverRevenue
	}
	return 0
}

type StatusEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentRef   string                 `protobuf:"bytes,1,opt,name=shipment_ref,json=shipmentRef,proto3" json:"shipment_ref,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Remarks       string                 `protobuf:"bytes,4,opt,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusEvent) Reset() {
	*x = StatusEvent{}
	mi := &file_api_proto_shipment_v1_shipment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusEvent) ProtoMessage() {}

func (x *StatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shipment_v1_shipment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusEvent.ProtoReflect.Descriptor instead.
func (*StatusEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_shipment_v1_shipment_proto_rawDescGZIP(), []int{1}
}

func (x *StatusEvent) GetShipmentRef() string {
	if x != nil {
		return x.ShipmentRef
	}
	return ""
}

func (x *StatusEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *StatusEvent) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

type CreateShipmentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReferenceNumber string                 `protobuf:"bytes,1,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	Origin          string                 `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination     string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	DriverDetails   string                 `protobuf:"bytes,4,opt,name=driver_details,json=driverDetails,proto3" json:"driver_details,omitempty"`
	UnitDetails     string                 `protobuf:"bytes,5,opt,name=unit_details,json=unitDetails,proto3" json:"unit_details,omitempty"`
	ShipmentAmount  float64                `protobuf:"fixed64,6,opt,name=shipment_amount,json=shipmentAmount,proto3" json:"shipment_amount,omitempty"`
	DriverRevenue   float64                `protobuf:"fixed64,7,opt,name=driver_revenue,json=driverRevenue,proto3" json:"driver_revenue,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateShipmentRequest) Reset() {
	*x = CreateShipmentRequest{}
	mi := &file_api_proto_shipment_v1_shipment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentRequest) ProtoMessage() {}

func (x *CreateShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shipment_v1_shipment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentRequest.ProtoReflect.Descriptor instead.
func (*CreateShipmentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shipment_v1_shipment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateShipmentRequest) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *CreateShipmentRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *CreateShipmentRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *CreateShipmentRequest) GetDriverDetails() string {
	if x != nil {
		return x.DriverDetails
	}
	return ""
}

func (x *CreateShipmentRequest) GetUnitDetails() string {
	if x != nil {
		return x.UnitDetails
	}
	return ""
}

func (x *CreateShipmentRequest) GetShipmentAmount() float64 {
	if x != nil {
		return x.ShipmentAmount
	}
	return 0
}

func (x *CreateShipmentRequest) GetDriverRevenue() float64 {
	if x != nil {
		return x.DriverRevenue
	}
	return 0
}

type CreateShipmentResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReferenceNumber string                 `protobuf:"bytes,1,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateShipmentResponse) Reset() {
	*x = CreateShipmentResponse{}
	mi := &file_api_proto_shipment_v1_shipment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentResponse) ProtoMessage() {}

func (x *CreateShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shipment_v1_shipment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentResponse.ProtoReflect.Descriptor instead.
func (*CreateShipmentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_shipment_v1_shipment_proto_rawDescGZIP(), []int{3}
}

func (x *CreateShipmentResponse) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

type GetShipmentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReferenceNumber string                 `protobuf:"bytes,1,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetShipmentRequest) Reset() {
	*x = GetShipmentRequest{}
	mi := &file_api_proto_shipment_v1_shipment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentRequest) ProtoMessage() {}

func (x *GetShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shipment_v1_shipment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shipment_v1_shipment_proto_rawDescGZIP(), []int{4}
}

func (x *GetShipmentRequest) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

type GetShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentResponse) Reset() {
	*x = GetShipmentResponse{}
	mi := &file_api_proto_shipment_v1_shipment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentResponse) ProtoMessage() {}

func (x *GetShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shipment_v1_shipment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentResponse.ProtoReflect.Descriptor instead.
func (*GetShipmentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_shipment_v1_shipment_proto_rawDescGZIP(), []int{5}
}

func (x *GetShipmentResponse) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

type AddShipmentEventRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReferenceNumber string                 `protobuf:"bytes,1,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Remarks         string                 `protobuf:"bytes,3,opt,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddShipmentEventRequest) Reset() {
	*x = AddShipmentEventRequest{}
	mi := &file_api_proto_shipment_v1_shipment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddShipmentEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShipmentEventRequest) ProtoMessage() {}

func (x *AddShipmentEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shipment_v1_shipment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShipmentEventRequest.ProtoReflect.Descriptor instead.
func (*AddShipmentEventRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shipment_v1_shipment_proto_rawDescGZIP(), []int{6}
}

func (x *AddShipmentEventRequest) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *AddShipmentEventRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AddShipmentEventRequest) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

type AddShipmentEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddShipmentEventResponse) Reset() {
	*x = AddShipmentEventResponse{}
	mi := &file_api_proto_shipment_v1_shipment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddShipmentEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShipmentEventResponse) ProtoMessage() {}

func (x *AddShipmentEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shipment_v1_shipment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShipmentEventResponse.ProtoReflect.Descriptor instead.
func (*AddShipmentEventResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_shipment_v1_shipment_proto_rawDescGZIP(), []int{7}
}

func (x *AddShipmentEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetShipmentHistoryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReferenceNumber string                 `protobuf:"bytes,1,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetShipmentHistoryRequest) Reset() {
	*x = GetShipmentHistoryRequest{}
	mi := &file_api_proto_shipment_v1_shipment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentHistoryRequest) ProtoMessage() {}

func (x *GetShipmentHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shipment_v1_shipment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shipment_v1_shipment_proto_rawDescGZIP(), []int{8}
}

func (x *GetShipmentHistoryRequest) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

type GetShipmentHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*StatusEvent         `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentHistoryResponse) Reset() {
	*x = GetShipmentHistoryResponse{}
	mi := &file_api_proto_shipment_v1_shipment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentHistoryResponse) ProtoMessage() {}

func (x *GetShipmentHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shipment_v1_shipment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetShipmentHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_shipment_v1_shipment_proto_rawDescGZIP(), []int{9}
}

func (x *GetShipmentHistoryResponse) GetEvents() []*StatusEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_api_proto_shipment_v1_shipment_proto protoreflect.FileDescriptor

const file_api_proto_shipment_v1_shipment_proto_rawDesc = "" +
	"\n" +
	"$api/proto/shipment/v1/shipment.proto\x12\vshipment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x02\n" +
	"\bShipment\x12)\n" +
	"\x10reference_number\x18\x01 \x01(\tR\x0freferenceNumber\x12\x16\n" +
	"\x06origin\x18\x02 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12%\n" +
	"\x0ecurrent_status\x18\x04 \x01(\tR\rcurrentStatus\x12%\n" +
	"\x0edriver_details\x18\x05 \x01(\tR\rdriverDetails\x12!\n" +
	"\funit_details\x18\x06 \x01(\tR\vunitDetails\x12'\n" +
	"\x0fshipment_amount\x18\a \x01(\x01R\x0eshipmentAmount\x12%\n" +
	"\x0edriver_revenue\x18\b \x01(\x01R\rdriverRevenue\"\x9c\x01\n" +
	"\vStatusEvent\x12!\n" +
	"\fshipment_ref\x18\x01 \x01(\tR\vshipmentRef\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\aremarks\x18\x04 \x01(\tR\aremarks\"\x96\x02\n" +
	"\x15CreateShipmentRequest\x12)\n" +
	"\x10reference_number\x18\x01 \x01(\tR\x0freferenceNumber\x12\x16\n" +
	"\x06origin\x18\x02 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12%\n" +
	"\x0edriver_details\x18\x04 \x01(\tR\rdriverDetails\x12!\n" +
	"\funit_details\x18\x05 \x01(\tR\vunitDetails\x12'\n" +
	"\x0fshipment_amount\x18\x06 \x01(\x01R\x0eshipmentAmount\x12%\n" +
	"\x0edriver_revenue\x18\a \x01(\x01R\rdriverRevenue\"C\n" +
	"\x16CreateShipmentResponse\x12)\n" +
	"\x10reference_number\x18\x01 \x01(\tR\x0freferenceNumber\"?\n" +
	"\x12GetShipmentRequest\x12)\n" +
	"\x10reference_number\x18\x01 \x01(\tR\x0freferenceNumber\"H\n" +
	"\x13GetShipmentResponse\x121\n" +
	"\bshipment\x18\x01 \x01(\v2\x15.shipment.v1.ShipmentR\bshipment\"v\n" +
	"\x17AddShipmentEventRequest\x12)\n" +
	"\x10reference_number\x18\x01 \x01(\tR\x0freferenceNumber\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\aremarks\x18\x03 \x01(\tR\aremarks\"4\n" +
	"\x18AddShipmentEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"F\n" +
	"\x19GetShipmentHistoryRequest\x12)\n" +
	"\x10reference_number\x18\x01 \x01(\tR\x0freferenceNumber\"N\n" +
	"\x1aGetShipmentHistoryResponse\x120\n" +
	"\x06events\x18\x01 \x03(\v2\x18.shipment.v1.StatusEventR\x06events2\x86\x03\n" +
	"\x0fShipmentService\x12Y\n" +
	"\x0eCreateShipment\x12\".shipment.v1.CreateShipmentRequest\x1a#.shipment.v1.CreateShipmentResponse\x12P\n" +
	"\vGetShipment\x12\x1f.shipment.v1.GetShipmentRequest\x1a .shipment.v1.GetShipmentResponse\x12_\n" +
	"\x10AddShipmentEvent\x12$.shipment.v1.AddShipmentEventRequest\x1a%.shipment.v1.AddShipmentEventResponse\x12e\n" +
	"\x12GetShipmentHistory\x12&.shipment.v1.GetShipmentHistoryRequest\x1a'.shipment.v1.GetShipmentHistoryResponseBNZLgithub.com/vonMeumann/shipment-grpc-service/api/proto/shipment/v1;shipmentv1b\x06proto3"

var (
	file_api_proto_shipment_v1_shipment_proto_rawDescOnce sync.Once
	file_api_proto_shipment_v1_shipment_proto_rawDescData []byte
)

func file_api_proto_shipment_v1_shipment_proto_rawDescGZIP() []byte {
	file_api_proto_shipment_v1_shipment_proto_rawDescOnce.Do(func() {
		file_api_proto_shipment_v1_shipment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_shipment_v1_shipment_proto_rawDesc), len(file_api_proto_shipment_v1_shipment_proto_rawDesc)))
	})
	return file_api_proto_shipment_v1_shipment_proto_rawDescData
}

var file_api_proto_shipment_v1_shipment_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_shipment_v1_shipment_proto_goTypes = []any{
	(*Shipment)(nil),                   // 0: shipment.v1.Shipment
	(*StatusEvent)(nil),                // 1: shipment.v1.StatusEvent
	(*CreateShipmentRequest)(nil),      // 2: shipment.v1.CreateShipmentRequest
	(*CreateShipmentResponse)(nil),     // 3: shipment.v1.CreateShipmentResponse
	(*GetShipmentRequest)(nil),         // 4: shipment.v1.GetShipmentRequest
	(*GetShipmentResponse)(nil),        // 5: shipment.v1.GetShipmentResponse
	(*AddShipmentEventRequest)(nil),    // 6: shipment.v1.AddShipmentEventRequest
	(*AddShipmentEventResponse)(nil),   // 7: shipment.v1.AddShipmentEventResponse
	(*GetShipmentHistoryRequest)(nil),  // 8: shipment.v1.GetShipmentHistoryRequest
	(*GetShipmentHistoryResponse)(nil), // 9: shipment.v1.GetShipmentHistoryResponse
	(*timestamppb.Timestamp)(nil),      // 10: google.protobuf.Timestamp
}
var file_api_proto_shipment_v1_shipment_proto_depIdxs = []int32{
	10, // 0: shipment.v1.StatusEvent.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: shipment.v1.GetShipmentResponse.shipment:type_name -> shipment.v1.Shipment
	1,  // 2: shipment.v1.GetShipmentHistoryResponse.events:type_name -> shipment.v1.StatusEvent
	2,  // 3: shipment.v1.ShipmentService.CreateShipment:input_type -> shipment.v1.CreateShipmentRequest
	4,  // 4: shipment.v1.ShipmentService.GetShipment:input_type -> shipment.v1.GetShipmentRequest
	6,  // 5: shipment.v1.ShipmentService.AddShipmentEvent:input_type -> shipment.v1.AddShipmentEventRequest
	8,  // 6: shipment.v1.ShipmentService.GetShipmentHistory:input_type -> shipment.v1.GetShipmentHistoryRequest
	3,  // 7: shipment.v1.ShipmentService.CreateShipment:output_type -> shipment.v1.CreateShipmentResponse
	5,  // 8: shipment.v1.ShipmentService.GetShipment:output_type -> shipment.v1.GetShipmentResponse
	7,  // 9: shipment.v1.ShipmentService.AddShipmentEvent:output_type -> shipment.v1.AddShipmentEventResponse
	9,  // 10: shipment.v1.ShipmentService.GetShipmentHistory:output_type -> shipment.v1.GetShipmentHistoryResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_shipment_v1_shipment_proto_init() }
func file_api_proto_shipment_v1_shipment_proto_init() {
	if File_api_proto_shipment_v1_shipment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_shipment_v1_shipment_proto_rawDesc), len(file_api_proto_shipment_v1_shipment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_shipment_v1_shipment_proto_goTypes,
		DependencyIndexes: file_api_proto_shipment_v1_shipment_proto_depIdxs,
		MessageInfos:      file_api_proto_shipment_v1_shipment_proto_msgTypes,
	}.Build()
	File_api_proto_shipment_v1_shipment_proto = out.File
	file_api_proto_shipment_v1_shipment_proto_goTypes = nil
	file_api_proto_shipment_v1_shipment_proto_depIdxs = nil
}
